version: '3.7'
services:

# Php
    php:
        build:
            context: ./
            dockerfile: Dockerfile.php
        working_dir: /var/www
        volumes:
            - ./:/var/www

# Web Server
    server:
        build:
            context: ./
            dockerfile: Dockerfile.server
        working_dir: /var/www
        ports:
            - 80:80

# Database
    mysql:
        image: mysql:5.7 #or postgres:11-alpine
        volumes:
            - dbdata:/var/lib/mysql
            #- or dbdata:/var/lib/postgresql/data
        environment:
            ## or POSTGRES_PASSWORD
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_USER: ${DB_USERNAME}
            MYSQL_PASSWORD: ${DB_PASSWORD}
        ports:
            - "3306:3306"

volumes:
    dbdata:
        driver: local
