version: "3"

services:
  nginx:
    image: nginx:1.17.9
    ports:
      - 89:80
    # - 443:443
    volumes:
      - ./src:/var/www:delegated
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:delegated
      - logsdata:/var/www/storage/logs
    depends_on:
      - php
    networks:
      - app-network
    restart: always

  mysql:
    image: mariadb:10.5
    restart: on-failure:3
    tty: true
    # ports:
    #   - "3306:3306"
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      SERVICE_TAGS: prod
      SERVICE_NAME: mysql
    volumes:
      - mysqldata:/var/lib/mysql
    networks:
      - app-network
    restart: always

  php:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./src:/var/www:delegated
    networks:
      - app-network
    restart: always

  redis:
    image: redis:6.0-alpine
    command: redis-server --requirepass ${REDIS_PASSWORD} --appendonly yes
    volumes:
      - redisdata:/data
    networks:
      - app-network
    restart: on-failure:3

  # adminer:
  #   image: adminer
  #   restart: always
  #   ports:
  #     - 8081:8080
  #   networks:
  #     - app-network

volumes:
  redisdata:
    driver: local
  mysqldata:
    driver: local
  logsdata:
    driver: local
networks:
  app-network:
    driver: bridge
