<template>
  <div>
    <img
      src="https://raw.githubusercontent.com/openjusticebe/ui-assets/main/svg/oj-animate.svg"
      alt="loading"
    />
    <div>
      <em>loading...</em>
    </div>
  </div>
</template>
